version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rachel_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rachel:
    build: .
    ports:
      - "4000:4000"  # Phoenix web server
      - "1982:1982"  # RUBP protocol server
    environment:
      DATABASE_URL: "ecto://postgres:postgres@postgres/rachel_dev"
      SECRET_KEY_BASE: "development_secret_key_base_at_least_64_characters_long_for_security_purposes"
      PHX_HOST: localhost
      PORT: 4000
      RUBP_PORT: 1982
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./lib:/app/lib
      - ./priv:/app/priv
      - ./config:/app/config
      - ./assets:/app/assets
    command: >
      sh -c "
        mix ecto.create &&
        mix ecto.migrate &&
        mix phx.server
      "

volumes:
  postgres_data: